#!/usr/bin/python3
import re
import subprocess

def get_resolution_from_file(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            # 从txt文件中读取内容
            m3u8_content = file.read()

            # 使用正则表达式提取M3U8文件中的链接和频道名称
            video_channels = re.findall(r'([^,]+),\s*(https?://[^\s]+)', m3u8_content)

            for channel_name, video_url in video_channels:
                print(f"获取到频道名称: {channel_name}")
                print(f"获取到视频链接: {video_url}")

                # 使用FFprobe获取分辨率信息（需要安装FFprobe）
                resolution_output = subprocess.check_output(['ffprobe', '-v', 'error', '-select_streams', 'v:0', '-show_entries', 'stream=width,height', '-of', 'csv=s=x:p=0', video_url])
                resolution = resolution_output.decode('utf-8').strip()
                print(f"视频分辨率: {resolution}")

                print("=" * 30)
    except FileNotFoundError:
        print(f"文件 '{file_path}' 未找到")

# 替换为你的M3U8文件路径
m3u8_file_path = 'IPTV.txt'
get_resolution_from_file(m3u8_file_path)
